version: '3.4'

services:
  naming-server:
    image: doflavio/naming-server:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
    networks:
      - doflavio-network
  
  zipkin-server:
    image: openzipkin/zipkin:2.23.2
    ports:
      - 9411:9411
    networks:
      - doflavio-network
      
  api-gateway:
    image: leandrocgsi/api-gateway:0.0.1-SNAPSHOT
    ports:
      - 8765:8765
    depends_on:
      - naming-server
      - rabbit-mq
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
    networks:
      - erudio-network
  
  
networks:
  doflavio-network:
    driver: bridge